name: publish

on:
  push:
    branches:
      - master

jobs:
  publish-sike-service-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build sike-service image
        run: |
          docker build . --tag ghcr.io/ashikka/sike-service

      - name: Push sike-service image
        run: |
          docker push ghcr.io/ashikka/sike-service
